-- Durable checkout idempotency around the non-idempotent Daribar order POST.
-- A cart instance is generated by the client, shared between browser tabs and
-- rotated after a completed checkout. Only its HMAC is stored here.

CREATE TABLE IF NOT EXISTS checkout_attempts (
    id                    uuid PRIMARY KEY,
    idempotency_key       text NOT NULL,
    actor_key             char(64) NOT NULL,
    cart_instance_key     char(64) NOT NULL,
    cart_hash             char(64) NOT NULL,
    request_hash          char(64) NOT NULL,
    state                 text NOT NULL CHECK (state IN ('pending', 'uncertain', 'replay')),
    response_status       integer CHECK (response_status BETWEEN 100 AND 599),
    response_payload      jsonb,
    provider_order_id     text,
    provider_started_at   timestamptz,
    lease_expires_at      timestamptz NOT NULL,
    retain_until          timestamptz NOT NULL,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT checkout_attempts_response_state_check CHECK (
        (state = 'pending' AND response_status IS NULL AND response_payload IS NULL)
        OR
        (state IN ('uncertain', 'replay') AND response_status IS NOT NULL AND response_payload IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS checkout_attempts_actor_idempotency_uidx
    ON checkout_attempts (actor_key, idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS checkout_attempts_actor_cart_instance_uidx
    ON checkout_attempts (actor_key, cart_instance_key);
CREATE INDEX IF NOT EXISTS checkout_attempts_retain_until_idx
    ON checkout_attempts (retain_until)
    WHERE state = 'replay';

COMMENT ON TABLE checkout_attempts IS
    'Durable replay/uncertainty guard for Daribar order creation; contains no raw customer data. Pending and uncertain rows require explicit reconciliation and are never garbage-collected automatically.';
